### ISSUE TITLE
Its say no module open ai found

### ISSUE THREAD

**Issue by KintCark** [MrHacker-X/ArtifyX#4]
I installed everything step by step I put my open ai key into the nano config but everytime I tryvto start the python script it says no model named openai found idk what's causing this but its not working for me this the 4thbtime I tried it. I saw someone on YouTube got it running but it's not working please help

**Comment by KintCark** [comment]
![Screenshot_20240123_211353_Termux](https://github.com/MrHacker-X/ArtifyX/assets/101164907/ce35a768-4c2f-44c1-9d04-2d31c27b060a)

**Comment by MrHacker-X** [comment]
If it's missing then simply install it by 

pip install openai
